openapi: 3.0.3
info:
  title: Fami Finance
  description: Trang web quản lý tài chính cá nhân
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  /:
    get:
      summary: Dashboard API
      responses:
        '200':
          description: dashboard object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                    example: 128
                  user:
                    type: string
                    example: Vuong NDV
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int32
                          example: 12345
                        title:
                          type: string
                          example: A new transaction title
