### Sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "vndv2@c.com",
  "password": "123123123",
  "firstName": "Vương"
}

### Sign in
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "vndv2@c.com",
  "password": "123123123"
}

### Sign out
DELETE http://localhost:3000/auth/signout
Content-Type: application/json

### Who am I
GET http://localhost:3000/auth/whoami
Content-Type: application/json
